site_name: Python Ember Mug
site_description: Unofficial Python API for interacting with Ember devices over Bluetooth
site_url: https://sopelj.github.io/python-ember-mug
repo_url: https://github.com/sopelj/python-ember-mug
repo_name: sopelj/python-ember-mug
edit_uri: edit/main/docs/

watch:
  - ember_mug

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  - Usage:
      - Installation: usage/installation.md
      - CLI: usage/cli.md
      - Python: usage/python.md
  - API Reference:
      - ember_mug: api/
  - Contributing: contributing.md
  - Changelog: changelog.md

theme:
  name: material
  icon:
    logo: material/coffee
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-night
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      accent: brown
      toggle:
        icon: material/weather-sunny
        name: Light mode
  features:
    - content.tooltips
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - admonition
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - meta
plugins:
  - include-markdown
  - autorefs
  - termynal
  - gen-files:
      scripts:
        - docs/gen_api_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [ember_mug]
          options:
            docstring_options:
              ignore_init_summary: true
            allow_inspection: true
            annotations_path: full
            docstring_section_style: table
            filters: ["!^_"]
            find_stubs_package: true
            inherited_members: true
            members_order: alphabetical
            modernize_annotations: true
            group_by_category: true
            separate_signature: true
            show_category_heading: true
            show_if_no_docstring: true
            show_labels: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_signature: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sopelj
      name: Github
    - icon: material/email
      link: "mailto:jesse.sopel@gmail.com"
